import {expect,test} from "@playwright/test";
import fs from "node:fs";import path from "node:path";
const output=path.resolve("artifacts/review/home/after");
const sizes=[{width:1440,height:900},{width:1024,height:768},{width:768,height:1024},{width:390,height:844}];

test("responsive scene, readable rail and immediate feedback",async({page})=>{
  fs.mkdirSync(output,{recursive:true});const errors:string[]=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));
  for(const size of sizes){await page.setViewportSize(size);await page.goto("/",{waitUntil:"networkidle"});await expect(page.locator("main")).toHaveAttribute("data-ready","true");if(size.width>620)await expect(page.locator("main")).toHaveAttribute("data-rail-visible","true");else{await page.getByRole("navigation",{name:"Featured experiences"}).scrollIntoViewIfNeeded();await expect(page.locator("main")).toHaveAttribute("data-rail-visible","true");await page.evaluate(()=>{scrollTo(0,0);const main=document.querySelector("main");if(main)main.setAttribute("data-force-rail","true");(document.activeElement as HTMLElement|null)?.blur()});await page.mouse.move(380,300)}
    await expect(page.getByRole("heading",{name:"NEXFIELD"})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBe(size.width);
    await page.screenshot({path:path.join(output,`home-${size.width}x${size.height}.png`),fullPage:true});
  }
  await page.setViewportSize({width:1440,height:900});await page.goto("/",{waitUntil:"networkidle"});
  const brand=page.getByRole("heading",{name:"NEXFIELD"}),hero=brand.locator("..");const initialGeometry=await brand.evaluate(element=>{const style=getComputedStyle(element),box=element.getBoundingClientRect(),parent=element.parentElement!.getBoundingClientRect();return{opacity:Number(style.opacity),clip:style.clipPath,width:box.width,top:box.top,parentTop:parent.top}});expect(initialGeometry.opacity).toBe(1);expect(initialGeometry.clip).not.toContain("100%");await page.waitForTimeout(1900);const settledPrism=await brand.evaluate(element=>{const line=getComputedStyle(element.nextElementSibling!),box=element.getBoundingClientRect(),parent=element.parentElement!.getBoundingClientRect();return{background:getComputedStyle(element).backgroundImage,opacity:Number(getComputedStyle(element).opacity),clip:getComputedStyle(element).clipPath,pseudo:getComputedStyle(element,"::before").content,lineOpacity:Number(line.opacity),lineTransform:line.transform,width:box.width,top:box.top,parentTop:parent.top}});expect(settledPrism.background).toContain("linear-gradient");expect(settledPrism.opacity).toBe(1);expect(settledPrism.clip).not.toContain("100%");expect(settledPrism.pseudo).toBe("none");expect(settledPrism.lineOpacity).toBeGreaterThanOrEqual(.5);expect(settledPrism.lineTransform).not.toContain("matrix(0,");expect(Math.abs(settledPrism.width-initialGeometry.width)).toBeLessThan(.1);expect(Math.abs(settledPrism.top-initialGeometry.top)).toBeLessThan(.1);expect(Math.abs(settledPrism.parentTop-initialGeometry.parentTop)).toBeLessThan(.1);await expect(hero).toBeVisible();
  for(const [name,file] of [["Signal Playground","hover-signal-playground.png"],["AI Radar","hover-ai-radar.png"],["AI Vision","hover-ai-vision.png"]] as const){
    await page.goto("/",{waitUntil:"networkidle"});const link=page.getByRole("link",{name:new RegExp(name)}).last(),description=link.locator("span").filter({hasText:/\.$/}).last();expect(Number(await description.evaluate(e=>getComputedStyle(e).opacity))).toBe(1);const box=await link.boundingBox();expect(box).not.toBeNull();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.waitForTimeout(100);await expect(page.locator("main")).toHaveAttribute("data-mode","neutral");expect(await link.locator("span").first().evaluate(e=>getComputedStyle(e).transform)).not.toBe("none");await page.waitForTimeout(300);await page.screenshot({path:path.join(output,file),clip:{x:0,y:76,width:1440,height:752}});await link.focus();await expect(link).toBeFocused();await link.blur();await page.mouse.move(10,200);await expect(page.locator("main")).toHaveAttribute("data-mode","neutral")
  }expect(errors).toEqual([]);
});

test.use({video:"on"});
test("load, hover timing and scroll choreography",async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto("/");await page.waitForTimeout(900);const rail=page.getByRole("navigation",{name:"Featured experiences"});await rail.scrollIntoViewIfNeeded();await page.waitForTimeout(450);for(const name of ["Signal Playground","AI Radar","AI Vision"]){const link=page.getByRole("link",{name:new RegExp(name)}).last();await link.hover();await page.waitForTimeout(420);await page.mouse.move(12,350);await page.waitForTimeout(230)}await page.evaluate(()=>scrollTo({top:0,behavior:"smooth"}));await page.waitForTimeout(800);await expect(page.locator("main")).toHaveAttribute("data-ready","true")});
